server:
  port: 8202

spring:
  application:
    name: xebs-server-test
  boot:
    admin:
      client:
        url: http://${xebs-monitor-admin}:8401
        username: xebs
        password: 123456
  zipkin:
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1
  rabbitmq:
    host: ${rabbitmq.url}
    port: 5672
    username: xebs
    password: 123456
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,com.baomidou.dynamic.datasource.spring.boot.autoconfigure.DynamicDataSourceAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

eureka:
  instance:
    lease-renewal-interval-in-seconds: 20
  client:
    register-with-eureka: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 30
    registry-fetch-interval-seconds: 3
    serviceUrl:
      defaultZone: http://xebs:123456@${xebs-register}:8001/register/eureka/

security:
  oauth2:
    resource:
      id: ${spring.application.name}
      user-info-uri: http://${xebs-gateway}:8301/auth/user

feign:
  hystrix:
    enabled: true

hystrix:
  shareSecurityContext: true

info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
