server:
  port: 8301

spring:
  application:
    name: xebs-gateway
  boot:
    admin:
      client:
        url: http://${xebs-monitor-admin}:8401
        username: xebs
        password: 183759
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

eureka:
  instance:
    lease-renewal-interval-in-seconds: 20
  client:
    register-with-eureka: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 30
    registry-fetch-interval-seconds: 3
    serviceUrl:
      defaultZone: http://xebs:123456@${xebs-register}:8001/register/eureka/

zuul:
  routes:
    auth:
      path: /auth/**
      serviceId: xebs-auth
      sensitiveHeaders: "*"
    system:
      path: /system/**
      serviceId: xebs-server-system
      sensitiveHeaders: "*"
    test:
      path: /test/**
      serviceId: xebs-server-test
      sensitiveHeaders: "*"
  retryable: true
  ignored-services: "*"
  ribbon:
    eager-load:
      enabled: true
  SendErrorFilter:
    error:
      disable: true

ribbon:
  ReadTimeout: 3000

info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
