server:
  port: 8001
  servlet:
    context-path: /register

spring:
  application:
    name: xebs-register   #定义服务名称
  security:
    user:
      name: xebs
      password: 123456
  boot:
    admin:
      client:
        url: http://localhost:8401  #指定了SBA服务端地址
        username: xebs              #对应SBA服务端的用户名
        password: 123456            #对应SBA服务端的密码
info: #配置了SBA客户端的名称，描述和版本信息
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"

management:
  endpoints:
    web:
      exposure:
        include: '*'   #表示将SBA客户端的所有监控端点都暴露给SBA服务端
  endpoint:
    health:
      show-details: ALWAYS   #表示总是展示详细的健康信息

eureka:
  instance:
    hostname: localhost  #指定了Eureka服务端的地址，因为我们是在本地搭建的，所以填写为localhost即可
  client:
    register-with-eureka: false  #表示是否将服务注册到Eureka服务端，由于我们这里是单节点的Eureka服务端，所以这里指定false
    fetch-registry: false
    instance-info-replication-interval-seconds: 30
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}${server.servlet.context-path}/eureka/
